### PR TITLE
Add `Content-Type: application/json` in curl examples

### PR DESCRIPTION
**Pull request by Wauplin**
Related to [slack thread](https://huggingface.slack.com/archives/C016D661PAN/p1694595733748539) (internal) cc @osanseviero @Narsil @julien-c 

Models served on Inference API with TGI (e.g meta-llama/Llama-2-70B-chat-hf) requires `'Content-Type: application/json'` to be set as header otherwise the server throws an error (_Expected request with Content-Type: application/json_). Let's add it to the cURL snippets to be consistent even if models served with `transformers` don't need it.

Another possibility would be to [disable the check on TGI side](https://huggingface.slack.com/archives/C016D661PAN/p1694596312771789?thread_ts=1694595733.748539&cid=C016D661PAN).

**EDIT:** it's also possible to add the header only to the text-generation snippets. Seems a bit inconsistent to me but I can update the PR if needed.

### CODE REVIEW

**Review by julien-c — COMMENTED** [review]
personally think it's fine to add it everywhere, but would stick it just after the actual payload

(more logical place imo)

**Comment by Wauplin** [comment]
> would stick it just after the actual payload

Right, I just made the change.

**Review by osanseviero — APPROVED** [review]
LGTM, thanks a lot!

**Comment by Wauplin** [comment]
Thanks for the review, I'm merging this :)

**Pull request merged**
