### PR TITLE
Update repositories-pull-requests-discussions.md

### PR DESCRIPTION
**Pull request by mishig25**
Update the PR git snippets:
1. Fuse step 1 & step 2
2. Use {PR_NUMBER} & give examples in Step 2 & Step 3

Before:
Screenshot 2022-08-02 at 15 23 53

After:
Screenshot 2022-08-02 at 15 32 26

### CODE REVIEW

**Review by coyotte508 — APPROVED** [review]

**Review by osanseviero — APPROVED** [review]
LGTM! Thanks!

**Comment by mishig25** [comment]
@julien-c good to merge?

**Comment by julien-c** [comment]
sounds reasonable

pinging @SBrandeis for a final review

**Review by SBrandeis — APPROVED** [review]
LGTM 👍

**Pull request merged**
