### PR TITLE
Added `About markdown` for text2text generation

### PR DESCRIPTION
**Pull request by akshay-babbar**
Hi Team/Maintainers, i saw the [tasks documentation](https://huggingface.co/tasks/text2text-generation) here was open to contribution. So for text2text generation task, i have updated the About md & open to updating the data.ts too.
Since this is is my first contribution to open source, would really be thankful if someone could guide me through this PR process.
Looking forward to hearing.
Thanks, 
Akshay

### CODE REVIEW

**Comment by merveenoyan** [comment]
Hello @akshay-babbar, we are about to remove text2text generation task page since it's already covered under text-generation one. Can you see if your contributions could fit that page and contribute to that one instead?

**Comment by akshay-babbar** [comment]
> 
Okay, please review a separate PR that i have created for feature extraction task then & let me know the feedback :)

**Comment by merveenoyan** [comment]
@akshay-babbar I left a review, but you can handle this one in this PR if this sounds good for you! (or feel free to open a separate one 🙂)

**Comment by merveenoyan** [comment]
@akshay-babbar would you like to open a separate PR or move on with this?

**Comment by akshay-babbar** [comment]
Hi @merveenoyan , closing this as you said that it's already covered under text-generation one. Thanks.

**Pull request closed without merging**
