### PR TITLE
Modify for doc-builder

### PR DESCRIPTION
**Pull request by mishig25**
Setup for doc-builder; test it at https://moon-ci-docs.huggingface.co/docs/hub/pr_145/

1. mv `docs/hub/_sections.yml` -> `docs/hub/_toctree.yml`
2. add github doc-builder workflows
3. mv `docs/hub/hugging-face-hub.md` -> `docs/hub/index.md`
4. rm folder `docs/hub/deprecated/`
5. mv `docs/assets/hub/` imgs -> https://huggingface.co/datasets/huggingface/documentation-images/tree/main/hub

What are we getting with doc-builder:
1. Nested left navbar
2. "Nicer" index page that lists all the sections in card/table style

Screenshot 2022-05-17 at 11 28 57

### CODE REVIEW

**Review by stevhliu — COMMENTED** [review]
This looks fire! 🔥 Some general thoughts:

- For the cards on the index page, I'm wondering if it would be better to replace all the individual links with a short description of each section and a link to their main pages (`repositories-main`, `models-main`, `spaces-main`, etc.). When we add more content in the future, it may be hard to fit all the section links into the card (the Models one is already quite full).

- The [CO2 section](https://moon-ci-docs.huggingface.co/docs/hub/pr_145/en/models-cards#cosub2sub-emissions) in the right navbar shows the HTML tags: `CO<sub>2</sub> Emissions`.

-  I noticed the nested sections don't have a little triangle next to them. I think adding these would maybe help readers navigate a little better by indicating they can expand the section to see more.

Screen Shot 2022-05-17 at 1 52 17 PM

**Comment by NimaBoscarino** [comment]
This looks awesome! I should have one last big content PR up today with the docs for organizations, the API, and settings/security. I guess once that's merged, then this could be merged on top of that, and then I can make a polishing PR to finish it all off.

In total there will be seven sections (Repositories, Models, Datasets, Spaces, Organizations, Settings, API). Do we want a big tile for each one? And if we do want a tile for each section, do we want the tiles to show links to pages, or would it be less cluttered to make it like the [main docs layout](https://huggingface.co/docs)?

**Comment by mishig25** [comment]
Regarding 
from @stevhliu 
> For the cards on the index page, I'm wondering if it would be better to replace all the individual links with a short description of each section and a link to their main pages (repositories-main, models-main, spaces-main, etc.). When we add more content in the future, it may be hard to fit all the section links into the card (the Models one is already quite full).

& from @NimaBoscarino 
> In total there will be seven sections (Repositories, Models, Datasets, Spaces, Organizations, Settings, API). Do we want a big tile for each one? And if we do want a tile for each section, do we want the tiles to show links to pages, or would it be less cluttered to make it like the [main docs layout](https://huggingface.co/docs)?

I'm happy to modify whatever the change desired. Ultimately, with the index page, I tried to copy github docs where you can quickly see the structure of docs & can navigate easily

| gh | hf |
|----|----|
| Screenshot 2022-05-19 at 10 24 29   |   Screenshot 2022-05-19 at 10 25 05 |

**Comment by osanseviero** [comment]
:fire: :fire: :fire: 

- I think Organizations, Settings, API could be in a fifth tile called Others.
- Right now, https://moon-ci-docs.huggingface.co/docs/hub/pr_145/en/repositories-main has a table of contents, is the idea to replace that with something with a nicer design?
- As for the design of the tiles, I'll let @gary149 provide his expertise :fire:

**Comment by mishig25** [comment]
@stevhliu added the little triangles for the nested sections on hover

Screenshot 2022-05-19 at 12 12 51

**Pull request merged**
