### PR TITLE
Task placeholder pages

### PR DESCRIPTION
**Pull request by beurkinger**
tied to https://github.com/huggingface/moon-landing/pull/4001

### CODE REVIEW

**Comment by merveenoyan** [comment]
@beurkinger I checked every task, thanks a lot for working on this!
My preference is to put multimodal section on bottom or middle since people landing to hf.co/tasks seeing that the pages are empty might want to see content for existing pages. 
Ekran Resmi 2022-09-28 16 24 47

Also for the empty ones, can we put something that indicates it's empty and requires a contribution? (like below)
task card

Also I can't see `about.md` for placeholder tasks, is it normal?

**Comment by beurkinger** [comment]
@merveenoyan please direct your comment for the UI to https://github.com/huggingface/moon-landing/pull/4001 :)

(this PR only address the data side of things)

**Review by merveenoyan — APPROVED** [review]
LGTM 🙂

**Review by osanseviero — APPROVED** [review]
Conceptually LGTM!

**Pull request merged**
