### PR TITLE
Update Space to dataset storage docs

### PR DESCRIPTION
**Pull request by Wauplin**
This PR updates the "Data Persistence for Spaces" section ([here](https://huggingface.co/docs/hub/spaces-storage#dataset-storage) and [here](https://huggingface.co/docs/hub/spaces-sdks-docker#data-persistence)) to showcase `CommitScheduler` instead of `Repository` with this [example Space](https://huggingface.co/spaces/Wauplin/space_to_dataset_saver) and [this guide](https://huggingface.co/docs/huggingface_hub/main/en/guides/upload#scheduled-uploads).

### CODE REVIEW

**Review by osanseviero — COMMENTED** [review]
I'm not 100% sure about this change. The schedule commit setup is nice but a bit complex to set up compared to just repository. Should we add a simple commit example to the guide?

**Comment by Wauplin** [comment]
> The schedule commit setup is nice but a bit complex to set up compared to just repository.

Maybe it is the docs/Space that are not simple enough which makes it looks as a complicated setup. Because IMO it really isn't that complex to use `CommitScheduler` as long as you don't care about the data format (e.g. being compatible with dataset-preview). Complexity about the data format is the same with the scheduler or a git clone since it's a matter of "how to save the data".

Basically, the setup goes from 

```py
repo = Repository(
    local_dir="data/", clone_from=DATASET_REPO_URL, use_auth_token=HF_TOKEN
)
repo.push_to_hub()  # on every call
```

to

```py
scheduler = CommitScheduler(
    repo_id=DATASET_ID, repo_type="dataset", folder_path="data/", token=HF_TOKEN
)
```

**Review by osanseviero — APPROVED** [review]

**Comment by osanseviero** [comment]
Feel free to resolve the conflict and merge, thanks a lot!

**Comment by Wauplin** [comment]
Lol, thanks for reviving this PR @coyotte508!

**Comment by Wauplin** [comment]
Conflict resolved, I'm merging. Thanks for the reminder!

**Pull request merged**
