### PR TITLE
Proposal: Slightly better than `getDemoInputs` already

### PR DESCRIPTION
**Pull request by julien-c**
Re. the `/// TODO(get rid of useless getDemoInputs)` comment introduced in #979

### CODE REVIEW

**Review by SBrandeis — COMMENTED** [review]
Clean!

**Comment by mishig25** [comment]
looks good to me. Do you want me to finish the PR (i.e. apply this change to other widgets)?

**Comment by julien-c** [comment]
yes sounds good @mishig25!

**Comment by mishig25** [comment]
Superceded by https://github.com/huggingface/hub-docs/pull/1023

**Pull request closed without merging**
