### PR TITLE
Add video classification task

### PR DESCRIPTION
**Pull request by nateraw**
Adds video classification as supported task.

Related convo: https://github.com/huggingface/hub-docs/issues/275

Haven't viewed this in moon landing yet, so leaving as draft until I do.

### CODE REVIEW

**Comment by nateraw** [comment]
Here it is in browser

Screen Shot 2022-10-18 at 6 28 25 PM

**Comment by osanseviero** [comment]
I think this is just using visual input, so I would leave in CV for now (although I could also see a case for multimodal if we use the audio as an input as well). No strong opinion

**Comment by julien-c** [comment]
icon looks good to me but still tagging @gary149

**Comment by osanseviero** [comment]
Should we go ahead with this PR or @gary149 you wanna take a look?

**Review by gary149 — APPROVED** [review]
LGTM

**Pull request merged**
