### PR TITLE
Hacktoberfest: no-license models challenge

### PR DESCRIPTION
**Pull request by Wauplin**
Similar to https://github.com/huggingface/hub-docs/pull/981.

This time I selected models that have 1 LICENSE file but no `license` metadata at all.
I only selected models with at least 1 download and 1 like to filter out most of minor ones.

cc @davanstrien @osanseviero 

See rendered markdown: https://github.com/huggingface/hub-docs/blob/hacktoberfest-challenges-no-license/hacktoberfest_challenges/model_no_license.md
And CSV: https://github.com/huggingface/hub-docs/blob/hacktoberfest-challenges-no-license/hacktoberfest_challenges/model_no_license.csv

### CODE REVIEW

**Review by julien-c — COMMENTED** [review]
i might be missing something but what is the difference between `model_license_other` and `model_no_license`?

Also when there is both a CSV and a markdown table, are they duplicate of each other? Which tools do you use to sync them?

**Comment by julien-c** [comment]
got it, thanks! and i should have commented on #981 i guess:)

**Review by davanstrien — APPROVED** [review]
Think this looks good. I suspect that people may run across the odd weird licence but hopefully they are mostly fairly standard.

**Comment by Wauplin** [comment]
Yep agree with you @davanstrien :grimacing: Let's see how it goes. Most of them should be "ok" licenses + interaction with the repo owners should also be interesting!

So I merged this PR and opened a new ticket to launch the challenge: https://github.com/huggingface/hub-docs/issues/995!

**Pull request merged**
