### PR TITLE
Use 4-space indentation for the sample code in Streamlit/Gradio pages

### PR DESCRIPTION
**Pull request by whitphx**

### CODE REVIEW

**Review by osanseviero — APPROVED** [review]
Thanks!

**Comment by osanseviero** [comment]
Could you please also update the gradio guide? (the code within `predict` seems wrongly indented https://moon-ci-docs.huggingface.co/docs/hub/pr_654/en/spaces-sdks-gradio )

**Comment by whitphx** [comment]
Oh, yes. I will.

It would be better if we can apply lint/formatters to these code blocks in markdown files in the CI flows too :)

**Review by osanseviero — APPROVED** [review]
Thanks a lot! :fire:

**Comment by julien-c** [comment]
Kudos on the first PR @whitphx 🔥

**Pull request merged**
