### PR TITLE
Add new gemma license

### PR DESCRIPTION
**Pull request by osanseviero**

### CODE REVIEW

**Review by pcuenca — APPROVED** [review]
Thank you!

**Review by julien-c — COMMENTED** [review]
is this the id that they've been using in the repos?

**Comment by osanseviero** [comment]
No, they are using `other`. We'll need to update their repos, currently:

```
license: other
license_name: gemma-terms-of-use
license_link: https://ai.google.dev/gemma/terms
```

**Comment by julien-c** [comment]
yep i meant for `license_name` i.E. i would have used `gemma-terms-of-use` as the id here. No big deal though

**Pull request merged**
