### PR TITLE
Add docs about the /commit endpoint

### PR DESCRIPTION
**Pull request by coyotte508**
cc @Wauplin 

Any reason for the trailing `   	|` for each line in the table?

### CODE REVIEW

**Comment by julien-c** [comment]
include a screenshot :)

**Comment by coyotte508** [comment]
The docs are here: https://moon-ci-docs.huggingface.co/docs/hub/pr_348/en/api

**Comment by julien-c** [comment]
i would refer to a detailed section below the table because this is not super legible:

image

**Comment by coyotte508** [comment]
or we could overhaul the docs and use a swagger-like interface x)

**Comment by NimaBoscarino** [comment]
I don't think there's any reason for the trailing `|`, as far as I know. Overhauling the endpoints docs to use something like Swagger would be awesome 👍 In the meantime though I agree that the payload is too long for the table, so maybe defining the `json` portion under the table would be cool, like Julien suggested.

**Comment by osanseviero** [comment]
Closing this as it's outdated/stalled

**Pull request closed without merging**
