### PR TITLE
Add CI workflow to auto-generate api inference documentation

### PR DESCRIPTION
**Pull request by hanouticelina**
This PR adds an automated workflow to update the Inference API documentation whenever there are changes in the API tasks (https://huggingface.co/api/tasks). 

As this endpoint and model inference status are regularly updated, maintaining an up-to-date Inference API documentation requires to run the `hub-docs/scripts/api-inference/generate` script and open a PR manually. Also, as the Inference API documentation is getting more attention recently, we might expect more requests to update the documentation (example in this [internal slack message](https://huggingface.slack.com/archives/C016D661PAN/p1730455149494059)). This workflow will help avoid opening PRs manually each time the documentation needs to be updated.

The initial idea was to add a cron job to run this workflow automatically on a regular basis. Would it make sense to add this automatic schedule?

Also, I'm using the same GH action as the one mentioned [here](https://huggingface.slack.com/archives/CTKK32GE8/p1728641835292529) (private) to create the PR. I want to have a first feedback on this before asking for repository permissions to allow the bot to create pull requests. 

Note: All changes in the documentation are from running the `generate` scripts.

### CODE REVIEW

**Review by Wauplin — APPROVED** [review]
Thanks @hanouticelina, this makes perfect sense to have such a workflow!

Let's post [in slack](https://huggingface.slack.com/archives/CTKK32GE8/p1728641835292529) to get the GITHUB_TOKEN approval from the infra team (same as for the other 2 PRs)

**Comment by pcuenca** [comment]
Great idea!

**Comment by Wauplin** [comment]
Seems to (finally) work fine now! :) Learnt a few things on the pnpm side :smile: 
Let's wait for  https://github.com/huggingface/hub-docs/pull/1490 to be ready and merged before merging this one

**Comment by hanouticelina** [comment]
@Wauplin should we add a cron job for this one?

**Comment by Wauplin** [comment]
Yes, added it in the last commit ^

**Review by Wauplin — APPROVED** [review]
https://github.com/huggingface/hub-docs/pull/1489 looks good now, having only the `@huggingface/tasks` update makes sense IMO. 

Time to merge I think once the workflow trigger is reverted to a cron job :)

**Comment by hanouticelina** [comment]
thanks @Wauplin for the review! I reverted the workflow trigger to a cron job and I updated the PR body to specify that it also upgrades `@huggingface/tasks`. Let's merge :)

**Pull request merged**
