### PR TITLE
integration of pythae to hf-hub

### PR DESCRIPTION
**Pull request by clementchadebec**
As discussed with @osanseviero,  I am opening this PR as part of the integration process of the [pythae library](https://github.com/clementchadebec/benchmark_VAE) to the hub (see https://github.com/clementchadebec/benchmark_VAE/issues/24)

### CODE REVIEW

**Review by osanseviero — APPROVED** [review]
Very cool! :fire:

**Comment by osanseviero** [comment]
@clementchadebec how many existing models are there on the Hub with the tag at the moment?

**Comment by osanseviero** [comment]
Cool! I'm ok with merging and deploying this PR, but I'm a bit hesitant of deploying something that will add a filter button that leads to a single model. Would you be ok if I wait until there are a couple more?

**Comment by NimaBoscarino** [comment]
Looks like there are [some more models now](https://huggingface.co/models?other=pythae)! @osanseviero do we think it's ready to deploy?

**Comment by osanseviero** [comment]
Yes let's merge it!

**Pull request merged**
