### PR TITLE
hmm 🤔

### PR DESCRIPTION
**Pull request by julien-c**
Screenshot 2023-09-27 at 20 06 07

### CODE REVIEW

**Review by osanseviero — APPROVED** [review]
LGTM, although it would be nice to update the number of stars in those repos as well! ;)

**Comment by mishig25** [comment]
Here is a PR https://github.com/huggingface/hub-docs/pull/975

**Comment by julien-c** [comment]
> LGTM, although it would be nice to update the number of stars in those repos as well! ;)

I didn't understand this comment. Which repos?

**Comment by julien-c** [comment]
haha ok you mean in the widget sample input?

**Comment by julien-c** [comment]
this PR was more about the extraneous weird `s` btw. Merging to fix

**Pull request merged**
