### PR TITLE
Added inference code snippet to zero shot image classification markdown

### PR DESCRIPTION
**Pull request by p4arth**
I have added a short code snippet demonstrating zero-shot image classification to the markdown.

### CODE REVIEW

**Review by merveenoyan — COMMENTED** [review]
left minor comments, thanks a lot for working on this!

**Review by merveenoyan — APPROVED** [review]
Thanks a lot!

**Comment by p4arth** [comment]
thanks for approving! My first contribution to HF 🤗.

**Comment by merveenoyan** [comment]
@p4arth can you give me your hugging face handle so I can add it at the end of the page?

**Comment by p4arth** [comment]
it's "Paarth"

**Pull request merged**
