### PR TITLE
Enable VQA in search filters for models

### PR DESCRIPTION
**Pull request by osanseviero**

### CODE REVIEW

**Comment by NielsRogge** [comment]
Thanks for that, although I don't really know JavaScript :D

**Comment by osanseviero** [comment]
Me neither :D

**Comment by osanseviero** [comment]
Note that this is just a minor change. `hideInModels` makes the type not showable in the filters at left of hf.co/models. That's what this PR changes :)

**Comment by julien-c** [comment]
> Thanks for that, although I don't really know JavaScript :D

you don't have Copilot? =)

**Comment by julien-c** [comment]
(or even better CodeParrot)

**Pull request merged**
