### PR TITLE
[doc+snippets] No more `use_auth_token=True` needed

### PR DESCRIPTION
**Pull request by julien-c**
Keeping as draft until https://github.com/huggingface/huggingface_hub/pull/1064 lands in a release. (and subsequently in a transformers or diffusers release if those still pin a version of `huggingface_hub` – not sure right now)

### CODE REVIEW

**Comment by julien-c** [comment]
N.B.: This is for simplicity, passing `use_auth_token` is stil supported (with same potential params as before), it's just that it now defaults to True

**Review by osanseviero — APPROVED** [review]
LG! :fire:

**Comment by patrickvonplaten** [comment]
Nice! @patil-suraj @pcuenca @anton-l let's make sure we update the Diffusers docs here as well

**Comment by julien-c** [comment]
Making note to merge this around end-of-year!

**Pull request merged**
