### PR TITLE
docs: add Resource Groups API documentation

### PR DESCRIPTION
**Pull request by Kakulukian**
Public api for resource group

### CODE REVIEW

**Review by Pierrci — APPROVED** [review]
nice!

**Review by julien-c — COMMENTED** [review]
cool!

I think we also wanted to add the API docs about orgs' user management, @Kakulukian @Pierrci ?

**Comment by Pierrci** [comment]
ah yes, if it's not there already it would probably make sense to add it too, indeed!

**Comment by julien-c** [comment]
@Kakulukian can you update this part here to link or copy/paste your API doc?

image

**Pull request merged**
