### PR TITLE
Support reinforcement learning and robotics as dataset tags

### PR DESCRIPTION
**Pull request by mariosasko**
Asked for in https://github.com/huggingface/datasets/issues/6125

### CODE REVIEW

**Comment by lhoestq** [comment]
Sounds good to me :)

It would be empty so far though no ? We could add them and see if some datasets are coming up and if it stays empty we can re-hide them

**Comment by mariosasko** [comment]
Yes, I had the same thought. Maybe @julien-c @osanseviero can share their opinions.

**Comment by osanseviero** [comment]
There are some from @edbeeching for RL and 3 for robotics https://huggingface.co/datasets?other=robotics

I think adding a filter for 3 datasets is not super nice experience, so maybe just the RL ones for now? WDYT?

**Comment by StoneT2000** [comment]
Just chiming in here. I think robotics is quite separate given there are many other approaches like imitation learning and behavior cloning that would not fall under RL. An RL tag and robotics tag would be great! And my lab will likely be uploading several models/datasets surrounding these soon for benchmarking robotic manipulation in simulation and working with sim2real transfer.

**Review by osanseviero — APPROVED** [review]
LGTM given the above :fire:

**Comment by julien-c** [comment]
this has not been deployed yet, correct?

wanted to make a nice screenshot of the new tasks on https://huggingface.co/datasets =)

**Comment by StoneT2000** [comment]
Looks like its up now. Thank you all for the fast work! Glad to be one of the first datasets tagged under robotics :)

**Comment by osanseviero** [comment]
Awesome! @albertvillanova @simoninithomas let's do some comms for this :)

**Comment by julien-c** [comment]
yaaaay, looks good @StoneT2000!! we're ready for more datasets!

image

**Pull request merged**
