### PR TITLE
Add link to hfh space management docs

### PR DESCRIPTION
**Pull request by Wauplin**
Related to https://github.com/huggingface/huggingface_hub/pull/1243.
It is now possible to request hardware from `huggingface_hub`. Let's mention it in the docs.

### CODE REVIEW

**Comment by Wauplin** [comment]
Good idea. Will set a reminder

**Review by julien-c — COMMENTED** [review]
looks good!

**Comment by julien-c** [comment]
what's the status on this? should we merge?

**Comment by Wauplin** [comment]
Very soon (see https://huggingface.slack.com/archives/C02V5EA0A95/p1674207561296969). `v0.12` will hopefully happen beginning of next week. I'll take care of merging this PR afterward

**Comment by Wauplin** [comment]
We are good to go to merge this one! :)
(I can't do it though as PR is not approved and I can't approve myself cc @julien-c @osanseviero)

**Review by julien-c — APPROVED** [review]

**Pull request merged**
