### PR TITLE
Revert "Update model-card-annotated.md"

### PR DESCRIPTION
**Pull request by EziOzoani**
Reverts huggingface/hub-docs#1178

lets try to see why it's not merging successfully

### CODE REVIEW

**Comment by Wauplin** [comment]
Hi @EziOzoani, I'm not sure to understand the goal of this PR. What went wrong with https://github.com/huggingface/hub-docs/pull/1178? Is there an error somewhere?
(I'm fine with reverting it if it has been discussed somewhere but I'm a bit surprised)

**Comment by EziOzoani** [comment]
Yeah so 
I don’t know if it was during the GitHub EU down period yesterday but it looked all good to merge but then the merge broke

**Comment by Wauplin** [comment]
> it looked all good to merge but then the merge broke

which merge? PR #1178 looks already merged. Are you talking about another Pull Request?

**Comment by EziOzoani** [comment]
Oh it did 
My bad, then yeah I’ll just close this out
thank You 🤗

**Comment by Wauplin** [comment]
Great! Thanks for the clarification :)

**Pull request closed without merging**
