### PR TITLE
📝 Document webhooks.updatedRefs

### PR DESCRIPTION
**Pull request by coyotte508**
cc @Wauplin for viz

### CODE REVIEW

**Review by Wauplin — APPROVED** [review]
Thanks!

Just to be sure, does that mean `webhook.version` got updated from "3" to "4" or not? (in that case we should update it in the docs as well)

**Comment by coyotte508** [comment]
> Thanks!
> 
> Just to be sure, does that mean `payload.webhook.version` got updated from "3" to "4" or not? (in that case we should update it in the docs as well)

Nope, will only change the version on breaking changes (which I hope there are none)

**Review by osanseviero — APPROVED** [review]
Nice!

**Review by pcuenca — APPROVED** [review]
Great work, clear and concise imo 🔥

**Review by julien-c — COMMENTED** [review]
you should post about this publicly given it can unlock some cool use cases IMO

**Pull request merged**
