### PR TITLE
[Widget docs] Add screenshots for `examples outputs`

### PR DESCRIPTION
**Pull request by mishig25**
Follow up to [this comment](https://github.com/huggingface/hub-docs/issues/1010#issuecomment-1789297341), #978

### CODE REVIEW

**Comment by julien-c** [comment]
ah i meant more like a screenshot of the gallery inside model card

**Comment by mishig25** [comment]
> ah i meant more like a screenshot of the gallery inside model card

Are you referring to `<Gallery>` component @krampstudio developing inside moon ?

**Comment by julien-c** [comment]
> Are you referring to `<Gallery>` component @krampstudio developing inside moon ? If that is the case, I think this PR (adding images for widget outputs) doesn't hurt and we still have the todo

yes, but just a mockup we already have

**Review by julien-c — COMMENTED** [review]
image

^this is supposed to be text-classification

image


^this is supposed to be ASR

**Comment by mishig25** [comment]
Fixed them with https://github.com/huggingface/hub-docs/pull/1078

Initially, I wanted to have screenshots that only share `output` (not the `input`) with the code blocks above the screenshots to show users all kinds of different widget types. But I see that it can be quite confusing

**Comment by mishig25** [comment]
regarding [this comment](https://github.com/huggingface/hub-docs/pull/1076#issuecomment-1791164555), added screenshot as well in #1079 

https://huggingface.co/docs/hub/models-widgets#example-outputs

image

**Comment by julien-c** [comment]
yes, looks good^

**Pull request merged**
