### PR TITLE
Add JS snippets to task pages

### PR DESCRIPTION
**Pull request by merveenoyan**
This PR adds `huggingface.js` snippets for task inferences. I wasn't super sure of the snippets that take multiple inputs so this one only adds the ones that have single input for now. Will add them later.

### CODE REVIEW

**Review by coyotte508 — APPROVED** [review]
Thanks, LGTM!

**Review by xenova — COMMENTED** [review]
Looks great! 🥳

Just a general comment about the code snippets: when I was testing out the HF inference API a while ago, I found it a bit annoying to copy+paste the snippets, run the code, and then see nothing appear. Of course, the reason was because the result was being awaited but not saved to a variable. So, I'd write `const output = ... ; console.log(output);` to see the output. I know this is how it's done across the huggingface.js documentation, so it's probably not a big thing to change. Perhaps an alternative is just to show what the output will look like, with a "show output" `<summary>` tag (or something similar?)

Thoughts? 😋

**Comment by merveenoyan** [comment]
@xenova we are trying to keep these as minimal as possible, but I'd like to have @osanseviero's comment :)

**Comment by xenova** [comment]
> @xenova we are trying to keep these as minimal as possible, but I'd like to have @osanseviero's comment :)

Gotcha! 😄 I see that some of the pages (e.g. [object-detection](https://huggingface.co/tasks/object-detection)) already include example output:
image

so, it might not be necessary :)

**Pull request merged**
