### PR TITLE
Add the SegFormer blog post to Image Segmentation Task

### PR DESCRIPTION
**Pull request by segments-tobias**
Today, a blog post on how to "[Fine-Tune a Semantic Segmentation Model with a Custom Dataset](https://huggingface.co/blog/fine-tune-segformer)" was released on the HF blog (see [PR #234](https://github.com/huggingface/blog/pull/234)).

This PR links the blog post in the "Useful Resources" section of the Image Segmentation task.
It also adds the `segments/sidewalk-semantic` dataset and `segments-tobias/segformer-b3-finetuned-segments-sidewalk` model as an example.

### CODE REVIEW

**Comment by segments-tobias** [comment]
Any comments @merveenoyan ?

**Comment by merveenoyan** [comment]
@segments-tobias Thanks a lot for this PR and kudos for the blog post! 🎉🤩 For models and datasets, we want to keep it a bit more generic. Is it okay if you could commit a version that doesn't have them instead?

**Comment by segments-tobias** [comment]
Makes sense. Updated it now @merveenoyan !

**Comment by merveenoyan** [comment]
@segments-tobias Hey Tobias, changes look good to me! I recently added a new model to segmentation page, so it causes a merge conflict. Can you resolve that and I will approve?

**Comment by segments-tobias** [comment]
@merveenoyan I think it was because I accidentally left a comma in the data.ts file. Should be fixed now!

**Review by merveenoyan — APPROVED** [review]

**Comment by merveenoyan** [comment]
Thanks a lot!!! 🤗 @segments-tobias

**Pull request merged**
