### PR TITLE
Add docsUrl attribute to `interface LibraryUiElement`

### PR DESCRIPTION
**Pull request by mishig25**
## TLDR: Add `docsUrl` attribute to interface LibraryUiElement

see linked internal issue

### Note: libs that don't have hub docs
https://github.com/MaartenGr/BERTopic
https://github.com/pytorch/fairseq
https://github.com/flairNLP/flair
https://github.com/NVIDIA/NeMo
https://github.com/mlfoundations/open_clip
https://github.com/huggingface/peft
https://github.com/scikit-learn/scikit-learn
https://github.com/pyannote/pyannote-audio
https://github.com/TensorSpeech/TensorFlowTTS
https://fasttext.cc/
https://github.com/clementchadebec/benchmark_VAE

### CODE REVIEW

**Comment by osanseviero** [comment]
Definitely some of these we would like to add to the docs

https://github.com/MaartenGr/BERTopic @MaartenGr would you like to add a quick page similar to https://huggingface.co/docs/hub/span_marker ? 

https://github.com/pytorch/fairseq https://github.com/NVIDIA/NeMo and https://github.com/pyannote/pyannote-audio @Vaibhavs10 maybe can help here?
https://github.com/mlfoundations/open_clip maybe @rwightman or @merveenoyan ?
https://github.com/huggingface/peft https://github.com/scikit-learn/scikit-learn maybe @merveenoyan as well? 

cc @pcuenca

**Comment by Vaibhavs10** [comment]
Dope! Happy to help, sure! From the context I've gathered so far this means that we need a page similar to this (ESPNet) right?
https://huggingface.co/docs/hub/espnet

I can add this next week for NeMo and Pyannote-audio.
Idk much about fairseq (have worked more with fairseq2) - but if there's nobody with more experience than me then I'm happy to pick it up too.

**Comment by mishig25** [comment]
Btw, we can approve/merge this PR without needing all the libs to have docs pages. I just listed them in the description to keep track of them

**Comment by pcuenca** [comment]
@mishig25 I agree, we can open those in a follow-up PR

**Review by pcuenca — APPROVED** [review]

**Pull request merged**
