### PR TITLE
Adding MidiTok to models-libraries.md

### PR DESCRIPTION
**Pull request by Natooz**
Following the integration of the hub in [MidiTok](https://github.com/Natooz/MidiTok) (v2.1.7), this PR adds it to the list of libraries integrating it. 🤗

(I also took the liberty add some spaces to aligne the *Library* and *Description* columns on some lines to improve the formatting)

### CODE REVIEW

**Comment by Natooz** [comment]
(pinging @Wauplin and @osanseviero)

**Review by Wauplin — APPROVED** [review]
Looks good to me! Thanks for adding it to the list.
Will wait for @osanseviero's review just in case (who maintained this file much more than me :wink:)


(FIY, generated docs look like this :)

image

)

**Review by osanseviero — APPROVED** [review]
Very cool! Don't hesitate to also add a quick guide such as https://huggingface.co/docs/hub/adapter-transformers

**Comment by Natooz** [comment]
@osanseviero Thank you! 🤗
Noted, I will do. I first hesitated as there is no inference / widget integration (maybe in the future).

**Pull request merged**
