### PR TITLE
after adding license metadata, update table -> Model list

### PR DESCRIPTION
**Pull request by Ashish-Soni08**
model_id -> TheBloke/OpenAssistant-Llama2-13B-Orca-v2-8K-3166-GPTQ

### CODE REVIEW

**Review by Wauplin — APPROVED** [review]
Looks good to me! Thanks for opening the PR @Ashish-Soni08 and congratulation for your first contribution to HF! :hugs:

**Comment by Ashish-Soni08** [comment]
Thank you so much Wauplin :). It is addictive :p Do you think I can try to complete the list or leave some for other people? :D

**Comment by Wauplin** [comment]
> Thank you so much Wauplin :). It is addictive :p Do you think I can try to complete the list or leave some for other people? :D

Ahah feel free to complete as many as you can! :smile: And you can open a PR on Github for multiple PRs on Huggingface at once. Hacktoberfest is nearly over! :fire:

**Comment by Ashish-Soni08** [comment]
All right :) I will do some more. I was opening one for each so that its easier to check if everything I did is fine :)

**Pull request merged**
