### PR TITLE
Implement `ZeroShotImageClassificationWidget`

### PR DESCRIPTION
**Pull request by mishig25**
### API shape

input (similar to ZeroShotTextClassificationWidget [here](https://github.com/huggingface/hub-docs/blob/5686c85b0ddbb8e4b95d9718b4b2c6d626aa46c8/js/src/lib/components/InferenceWidget/widgets/ZeroShowClassificationWidget/ZeroShotClassificationWidget.svelte#L93-L99) with 2 differences: 1. [image](https://github.com/huggingface/hub-docs/blob/d77cebdbc57d158bd5a1043d25def73f2d54bff6/js/src/lib/components/InferenceWidget/widgets/ZeroShotImageClassificationWidget/ZeroShotImageClassificationWidget.svelte#L106) instead of [inputs](https://github.com/huggingface/hub-docs/blob/5686c85b0ddbb8e4b95d9718b4b2c6d626aa46c8/js/src/lib/components/InferenceWidget/widgets/ZeroShowClassificationWidget/ZeroShotClassificationWidget.svelte#L94), 2. NO [multi_class](https://github.com/huggingface/hub-docs/blob/5686c85b0ddbb8e4b95d9718b4b2c6d626aa46c8/js/src/lib/components/InferenceWidget/widgets/ZeroShowClassificationWidget/ZeroShotClassificationWidget.svelte#L97)):
```js
const requestBody = {
    image: imageBase64, // base64 str of image
    parameters: { 
        candidate_labels: trimmedCandidateLabels,
    },
};
```

output (identical to ZeroShotTextClassification widget [here](https://github.com/huggingface/hub-docs/blob/5686c85b0ddbb8e4b95d9718b4b2c6d626aa46c8/js/src/lib/components/InferenceWidget/widgets/ZeroShowClassificationWidget/ZeroShotClassificationWidget.svelte#L36)):
```js
Array<{ label: string; score: number }>
```

todos:
- [ ] test when api-inference is up
- [ ] test widget input samples
- [ ] document in hub-docs

@Narsil @OlivierDehaene please let me know if the API shape is looking correct & when the API-inference for this task is online

cc: @osanseviero

### CODE REVIEW

**Comment by osanseviero** [comment]
Part of #41

**Comment by Narsil** [comment]
I think it's still `inputs` not `image`, no ?

**Comment by mishig25** [comment]
@Narsil are you suggesting that https://github.com/huggingface/hub-docs/blob/d77cebdbc57d158bd5a1043d25def73f2d54bff6/js/src/lib/components/InferenceWidget/widgets/ZeroShotImageClassificationWidget/ZeroShotImageClassificationWidget.svelte#L105-L110
should be instead: 
```js
const requestBody = {
    inputs: imageBase64,
    parameters: {
        candidate_labels: trimmedCandidateLabels,
    },
};
```

?

**Comment by mishig25** [comment]
@OlivierDehaene thank a lot for the api-inference implementation.

The demo widget is [here](https://63341f546b64f07ab5e272c8--huggingface-widgets.netlify.app/openai/clip-vit-base-patch16). However, there is a small `split` problem, as you can see in the img below (cat, dog -> [c,a,t,d,o,g], should be [cat, dog])
image

However, in the api-inference impl, I do see [here](https://github.com/huggingface/api-inference/blob/a108903d8e2e77a6e823feba93489c3a7f1804bd/shard/app/validation.py#L93-L96)
```py
    def candidate_labels_max(cls, v):
        if isinstance(v, str):
            return v.split(",")
```

**Comment by OlivierDehaene** [comment]
@mishig25,
There is indeed a validation issue for the parameters. We are currently refactoring the validation logic in [this PR][https://github.com/huggingface/api-inference/pull/1156). Does it make sense for you to wait for this PR to be merged or do you want me to submit a hotfix?

**Comment by mishig25** [comment]
I can wait 😊

**Comment by OlivierDehaene** [comment]
@mishig25,
The PR landed and the demo widget seem to work now :) 
image

**Comment by mishig25** [comment]
@OlivierDehaene thanks a lot! 🚀

**Pull request merged**
