### PR TITLE
Add Space disk space info

### PR DESCRIPTION
**Pull request by osanseviero**
Related discussion https://huggingface.slack.com/archives/C048K60MPNF/p1675778705684199

### CODE REVIEW

**Review by christophe-rannou — APPROVED** [review]
LGTM but is it me or there is an issue with the PR doc https://moon-ci-docs.huggingface.co/docs/hub/pr_669/en/spaces-overview ?
I can't see your changes there.

Edit: was not patient enough, I see the changes now !

**Review by julien-c — APPROVED** [review]
LGTM but we'll also need to make sure to keep those up to date :)

cc @SBrandeis who controls the ground truth for the prices

**Comment by SBrandeis** [comment]
Would it make sens to display that information in the [pricing page](https://huggingface.co/pricing#spaces) instead, and maybe link to there from the docs?
It would avoid discrepancies between the docs and the actual prices / hardware specs, and keep moon-landing as the source of truth on that matter

**Comment by osanseviero** [comment]
WDYT @julien-c? You mentioned nicer in the docs that in /settings, but what about /pricing?

**Comment by julien-c** [comment]
no strong opinion – we can also merge them here for now, and think about it later

i.E. i think on /pricing for instance "disk space" might be a bit too much info, so i think it makes sense here

**Comment by osanseviero** [comment]
Alright, merging ahead then!

**Pull request merged**
