### PR TITLE
Enable download Git-LFS files on sync

### PR DESCRIPTION
**Pull request by radames**
Following an user issue, enable LFS on [sync](https://github.com/actions/checkout#:~:text=Whether%20to%20download%20Git%2DLFS%20files)

### CODE REVIEW

**Comment by NimaBoscarino** [comment]
What LFS files need to be downloaded for the build? AFAIK any image assets should be up on https://huggingface.co/datasets/huggingface/documentation-images, and I don't know if there are other binary files that would be part of the hub-docs. Holding off on approving, but otherwise this LGTM!

**Comment by radames** [comment]
hi @NimaBoscarino , thanks for the comment. The changes is only for the GitHub Action example when a user wants to sync their GitHub repository with a Space, and the action need to explicitly enable sync LFS files in the repo.
An user, for example, had onnx models in their GitHub repo, and need to LFS push to our hub. It wasn't working without that option  `lfs: true` .

**Review by osanseviero — APPROVED** [review]
Thanks for this! cc @nateraw as well

**Comment by NimaBoscarino** [comment]
@radames Oh LOL, I should have looked at the file name 🤦 I thought it was a GitHub action for this repo, hahahaha.

**Comment by radames** [comment]
> @radames Oh LOL, I should have looked at the file name 🤦 I thought it was a GitHub action for this repo, hahahaha.
haha no worries, I was a bit confused but fun 😂

**Pull request merged**
