### PR TITLE
Fix the Gradio example with working one

### PR DESCRIPTION
**Pull request by Bennoo**
The Gradio example with the hot-dog recog model is not working due to Gradio updates.

### CODE REVIEW

**Comment by Bennoo** [comment]
The Gradio example with the hot-dog model is not working anymore. Gradio evolved and usage changed a bit.
I changed the provided code with a working one (tested in a space)
The best will be to change also the pictures below the code example but I don't find how to do it.

**Review by julien-c — COMMENTED** [review]
tagging @abidlabs and team for a quick review on this!

**Comment by abidlabs** [comment]
Oh wow that syntax is from Gradio 2.x, thanks for updating @Bennoo! lgtm

**Review by abidlabs — APPROVED** [review]

**Review by julien-c — APPROVED** [review]

**Comment by Bennoo** [comment]
So happy to help! Huge fan here
BTW there is still a workflow to approve here to close this.
Thanks, guys for the awesome work at HuggingFace and Gradio!

**Pull request merged**
