### PR TITLE
Add gradio docker example

### PR DESCRIPTION
**Pull request by johko**
Hey, I recently was looking for a docker space example that just uses Gradio and it was harder to find than I thought.
I thought it would be nice to include @sayakpaul's space here in the general examples.

### CODE REVIEW

**Review by osanseviero — COMMENTED** [review]
Out of curiosity, why would a user prefer a Docker Space for Gradio rather than the native Gradio Space?

**Comment by sayakpaul** [comment]
So, I hit on a likely upcoming feature accidentally? I will take the day off to celebrate 🎉

**Comment by julien-c** [comment]
haha still interested in why you needed this, out of curiosity!

**Comment by sayakpaul** [comment]
So, I was working on [this Space](https://t.co/yvb2OPQ9je) that lets you optimize a ResNet50 model. The Space required a Docker support (TensorRT can sometimes destroy your mood out of nowhere). I wanted the results to be presentable and that is why I ended up exploring this integration: Docker + Spaces + Gradio.

**Comment by julien-c** [comment]
I see! that's a valid use case

**Comment by johko** [comment]
In my case pytorch3d is the culprit. It is hell to set up (even locally) without docker. And I want to use it in a space.

To save some time and not despair completely I'm using gradio inside a docker that has the pytorch3d environment all set up.

**Comment by johko** [comment]
Doing a quick search for "dockerfile gradio" with the new full-text search also reveals some spaces, which seem to be using Gradio from a docker container: https://huggingface.co/search/full-text?q=dockerfile+gradio&p=1&type=space
So it does not seem to be the rarest of use-cases I'd say

**Comment by osanseviero** [comment]
Cool, thanks for explaining! Could you please solve the merge conflict? I can merge afterwards

**Comment by johko** [comment]
thanks @osanseviero. the last commit has a confusing commit message, but should be good to go now

**Review by osanseviero — APPROVED** [review]
Thanks! 🔥

**Pull request merged**
