### PR TITLE
Bloom: add AzureML to the widget

### PR DESCRIPTION
**Pull request by gary149**
Only for Bloom:

image

### CODE REVIEW

**Review by mishig25 — APPROVED** [review]
lgtm!

**Comment by Michellehbn** [comment]
Hi @gary149 ! Looks good! One change needed:

"Sponsored by Azure Machine Learning" in place of "Powered by AzureML" and should link to https://azure.microsoft.com/en-us/products/machine-learning/.

**Comment by gary149** [comment]
> "Sponsored by Azure Machine Learning" in place of "Powered by AzureML" and should link to https://azure.microsoft.com/en-us/products/machine-learning/.

Ok, I can change it to "Sponsored by AzureML". This link [https://azure.microsoft.com/products/machine-learning](https://azure.microsoft.com/products/machine-learning) redirects depending on the user language so it should be even better.

**Comment by Michellehbn** [comment]
Hi @gary149 ! Just checked prod, https://huggingface.co/bigscience/bloom, and "Powered by AzureML" is showing. Do you mind updating to  "Sponsored by AzureML" please? TIA!

**Comment by Pierrci** [comment]
@Michellehbn see https://github.com/huggingface/hub-docs/pull/405

**Pull request merged**
