### PR TITLE
remove the mention given the app hasn't been maintained AFAIK

### PR DESCRIPTION
**Pull request by julien-c**

### CODE REVIEW

**Review by Wauplin — COMMENTED** [review]
> given the app hasn't been maintained

Or should we maintain it? Space still seems to be working. It has received 1470 visits on the last month

(we can remove the `New !` though)

**Review by osanseviero — APPROVED** [review]

**Comment by julien-c** [comment]
@Wauplin couple of pages are broken: 
image

for me in the context of the doc page https://huggingface.co/docs/hub/model-cards the app is not super useful

Note that i'm not proposing of removing or deprecating the Space, just the mention on that doc page (or we can put it somewhere else on the page, less visible?)

**Comment by Wauplin** [comment]
Fine for me then :)

**Comment by meg-huggingface** [comment]
Yes, I agree as well. Sounds good to me.

**Review by meg-huggingface — APPROVED** [review]
SGTM

**Pull request merged**
