### PR TITLE
Added tabular regression task and renamed Structured Data Classification widget

### PR DESCRIPTION
**Pull request by merveenoyan**
This PR adds `tabular-regression` task, it's icon and renames the widget and uses it for both tabular-classification and `tabular-regression` tasks (swapped `StructuredDataClassificationWidget` with `TabularDataWidget`)

### CODE REVIEW

**Comment by osanseviero** [comment]
You don't need Gitaly, you can just do `NODE_REPOS=0 npm run watch` and follow the process at https://github.com/huggingface/moon-landing#annex-quickndirty-way-to-run-blog-on-your-local-machine. You can either use docker or just use redis/mongo if you want something quick.

**Comment by merveenoyan** [comment]
@osanseviero I did start mongo and redis and I got errors regarding gitaly. I'm currently removing everything and start from scratch, it usually works when I do that :)

**Comment by osanseviero** [comment]
Partly fixes #137

**Comment by osanseviero** [comment]
There seems to be a merge conflict. Could you also add a screenshot of how the icon looks at the description of the PR please?

**Comment by merveenoyan** [comment]
Ekran Resmi 2022-06-01 18 24 53 (1)
I fixed the Task name at the "Adding a Task" page that's why there's a merge conflict.

**Comment by merveenoyan** [comment]
IDK why but my conflict was very small yet it said it was too big, didn't raise it as a conflict. 🤯  it's fine as is.

**Comment by merveenoyan** [comment]
Closing because it was easier to actually open another PR from a branch of a main repo (in favor of this https://github.com/huggingface/hub-docs/pull/176) I made my life harder 😅

**Pull request closed without merging**
