### PR TITLE
Image patch

### PR DESCRIPTION
**Pull request by EziOzoani**
MC user studies image patch

### CODE REVIEW

**Review by EziOzoani — COMMENTED** [review]
✔️

**Review by osanseviero — COMMENTED** [review]
Is this page supposed to be shown in hf.co/docs/hub? I go to https://moon-ci-docs.huggingface.co/docs/hub/pr_575/en/index#user-study-details but it redirects me to the main page

**Comment by EziOzoani** [comment]
@osanseviero it should be shown here: https://moon-ci-docs.huggingface.co/docs/hub/pr_575/en/model-cards-user-studies

however, that patch didn't help with displaying the images🤔 let me take another swing at it 👩‍💻 because the same problem persists here to; https://moon-ci-docs.huggingface.co/docs/hub/pr_575/en/model-card-landscape-analysis

**Comment by osanseviero** [comment]
Hi @EziOzoani! Is this still actively being worked on or should we close? I'll close for now but feel free to reopen it :fire:

**Pull request closed without merging**
