### PR TITLE
Remove the YAML breaks from example

### PR DESCRIPTION
**Pull request by davanstrien**
Possibly YAML markers are breaking build of docs

### CODE REVIEW

**Comment by julien-c** [comment]
(follow up to #645 )

For some reason now the doc build CI job fails 🤔

**Comment by davanstrien** [comment]
Building no longer fails, but the preview still returns a 500 error for page added in #645

**Comment by davanstrien** [comment]
> Building no longer fails, but the preview still returns a 500 error for page added in #645

I ran black on the code to enforce double quotes in the Python block to see if single quotes were causing issues, but this doesn't seem to have fixed the issue.

**Comment by julien-c** [comment]
can be closed if #649 solves the issue

**Pull request closed without merging**
