### PR TITLE
Add links to code of conduct and content guideline

### PR DESCRIPTION
**Pull request by NimaBoscarino**
This PR adds links to the code of conduct and the content guideline from the main hub-docs page.

### CODE REVIEW

**Review by Pierrci — APPROVED** [review]
LGTM, thanks @NimaBoscarino

**Comment by julien-c** [comment]
shouldn't they also be listed in the left sidebar here? 
image

**Comment by NimaBoscarino** [comment]
As far as I know, the left sidebar lists markdown pages and doesn't link to other URLs. I embedded the code of conduct and content guideline as URLs, since I didn't think that they warranted their own full page in the hub-docs. But if we want that, I can totally make a full page for it!

**Comment by osanseviero** [comment]
cc @mishig25. Is it possible to list external URLs in the sidebar in the docs?

**Comment by julien-c** [comment]
> As far as I know, the left sidebar lists markdown pages and doesn't link to other URLs. I embedded the code of conduct and content guideline as URLs, since I didn't think that they warranted their own full page in the hub-docs. But if we want that, I can totally make a full page for it!

oh yeah you're right I missed that

**Pull request merged**
