### PR TITLE
add snippets for image-to-text

### PR DESCRIPTION
**Pull request by xianbaoqian**
image
image
image

Request: https://github.com/huggingface/hub-docs/issues/735

### CODE REVIEW

**Comment by xianbaoqian** [comment]
(use gpt2 as an example)

**Comment by coyotte508** [comment]
Do we want to promote the official libs ? cc @Wauplin 

For example:

```ts
import { HfInference } from "@huggingface/inference";

const inference = new HfInference("hf_XXXXXX");

const text = await inference.imageToText({
  data: await (await fetch('https://picsum.photos/300/300')).blob(),
  model: "gpt2"
});
```

**Review by osanseviero — APPROVED** [review]
LGTM, thanks!

**Comment by xianbaoqian** [comment]
This new API looks cool.   Let me merge this one as it is. I'll create a new one to update all the snippets.   Maybe we can have both (if user would rather prefer not to use our library unfortunately).

**Pull request merged**
