### PR TITLE
Spaces: simple GPU instructions for PyTorch, JAX and tensorflow

### PR DESCRIPTION
**Pull request by pcuenca**
Fixes #3656.

I also updated the overview to mention upgrades. If you'd rather have this as a separate PR just let me know :)

### CODE REVIEW

**Comment by pcuenca** [comment]
Thanks for the suggestions @osanseviero! I just added them.

**Review by osanseviero — APPROVED** [review]
Awesome, thanks a lot :) feel free to merge whenever you're happy with the content

**Comment by pcuenca** [comment]
I love the new content and just fixed a typo in the link from `spaces.md`, so it's good to go in my opinion!

**Comment by julien-c** [comment]
alright feel free to merge! cc @gary149 for context too

**Comment by julien-c** [comment]
the CI failed on `main` so the doc hasn't been deployed to https://huggingface.co/docs/hub

Any idea why? cc @mishig25 too

**Comment by pcuenca** [comment]
@mishig25, I just saw you triggered a re-run and it worked this time, thanks a lot! Is there anything I should have done differently in the first place?

**Pull request merged**
