### PR TITLE
Fix Widget tokens color darkmode

### PR DESCRIPTION
**Pull request by mishig25**
Closes #768, closes https://github.com/huggingface/hub-docs/issues/12, closes https://github.com/huggingface/hub-docs/issues/764

cc: @tomaarsen

| before | after |
| --------- | --------- |
| Screenshot 2023-06-20 at 11 22 58    | Screenshot 2023-06-20 at 11 42 44    |

### CODE REVIEW

**Review by osanseviero — APPROVED** [review]
Thanks!

**Comment by julien-c** [comment]
nice, this was a longstanding issue:)

**Comment by tomaarsen** [comment]
Awesome! Glad to see this fixed, and glad to see that my investigation in #768 was useful. 
Also, fun to see one of my SpanMarker models being used to test this fix! Good job @mishig25

**Comment by mishig25** [comment]
@tomaarsen thanks a lot for all the help!

**Pull request merged**
