### PR TITLE
add bigcode license

### PR DESCRIPTION
**Pull request by lvwerra**
Adds the BigCode OpenRAIL license to the Hub.

### CODE REVIEW

**Review by julien-c — COMMENTED** [review]
it's a specific license? or we can use `openrail` maybe?

**Review by osanseviero — APPROVED** [review]

**Comment by osanseviero** [comment]
It's a specific license that was changed for BigCode

**Comment by osanseviero** [comment]
Internal discussion: https://huggingface.slack.com/archives/C03M3LKL4C8/p1683016451849279?thread_ts=1682626465.808009&cid=C03M3LKL4C8

**Comment by julien-c** [comment]
yes but my general point is that we should use the same "license tag" for multiple models otherwise the license tag makes no sense

**Comment by julien-c** [comment]
but ok to add this one, it's a more general point

**Pull request merged**
