### PR TITLE
Add an Example using Julia's Genie.jl framework

### PR DESCRIPTION
**Pull request by anoojpatel**
I've created a demo using Julia lang's Genie.jl framework to build a webapp using Docker spaces! I would love to add this to the list of examples, as it is quite finicky to figure out how ports need to be exposed and how the default CMD is leveraged. I think this would be useful for those looking to grow the Julia ecosystem and support on the Huggingface platform :)

### CODE REVIEW

**Review by julien-c — APPROVED** [review]
Very cool! Would you be up for writing a short write-up about how the steps you went through, (as well as a quick intro to Genie.jl) which we could have directly in hf.co/docs/hub?

**Comment by anoojpatel** [comment]
Yes definitely! Where should I put this specific write up?

**Comment by julien-c** [comment]
maybe in `spaces-docker-julia-genie.md` file? (we can always rename later if needed)

**Comment by julien-c** [comment]
in the meantime, i'm deploying this PR :) Thanks a lot!

**Comment by julien-c** [comment]
see also #585 for a similar approach! (documenting a new SDK for Spaces)

**Comment by apatel-fn** [comment]
Amazing! Thanks for the reference :)

**Pull request merged**
